### ISSUE TITLE
Bug: cmd+shift+R does not copy entire error log

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#133]
## Describe the bug

Should be: 
<img width="1474" alt="Screenshot 2024-06-11 at 7 10 50 AM" src="https://github.com/trypear/pearai-app/assets/5115108/c94ebe1d-73d5-486b-ab0d-4d341a4ec66f">

but is: 
<img width="1436" alt="Screenshot 2024-06-11 at 7 12 48 AM" src="https://github.com/trypear/pearai-app/assets/5115108/89eaea94-cba5-46c8-bd69-262a74921e4a">

## How to reproduce
Run  python3 extensions/vscode/pearai_tutorial.py and then do *cmd+shift+R* on continue, then using pear
## Expected behavior
Pear should copy the entire error message into the chat log

_Clear and concise description of what you expected to happen._

## Screenshots

_If applicable, add screenshots to help explain your problem._

## Additional information

- Version of the extension impacted: _vX.X.X_

_🧙‍ Add any other context about the problem here._

**Comment by nang-dev** [comment]
Relevant code block

`async getTerminalContents(commands: number = -1): Promise<string> {
    const tempCopyBuffer = await vscode.env.clipboard.readText();
    if (commands < 0) {
      await vscode.commands.executeCommand(
        "workbench.action.terminal.selectAll",
      );
    } else {
      for (let i = 0; i < commands; i++) {
        await vscode.commands.executeCommand(
          "workbench.action.terminal.selectToPreviousCommand",
        );
      }
    }
    await vscode.commands.executeCommand(
      "workbench.action.terminal.copySelection",
    );
    await vscode.commands.executeCommand(
      "workbench.action.terminal.clearSelection",
    );
    let terminalContents = (await vscode.env.clipboard.readText()).trim();
    await vscode.env.clipboard.writeText(tempCopyBuffer);

    if (tempCopyBuffer === terminalContents) {
      // This means there is no terminal open to select text from
      return "";
    }

    // Sometimes the above won't successfully separate by command, so we attempt manually
    const lines = terminalContents.split("\n");
    const lastLine = lines.pop()?.trim();
    if (lastLine) {
      let i = lines.length - 1;
      while (i >= 0 && !lines[i].trim().startsWith(lastLine)) i--;
      terminalContents = lines.slice(i).join("\n");
    }

    return terminalContents;
  }`

**Comment by nang-dev** [comment]
resolved without needing action

https://github.com/trypear/pearai-submodule/pull/46

**Comment by nang-dev** [comment]
oh its because i have a plugin that gives me special characters for errors: specifically:  ✘ 

nathanan@Nathans-MacBook-Air  ~/Documents/working-dir/pearai-app/extensions/pearai-submodule   main  hi
 ✘ nathanan@Nathans-MacBook-Air  ~/Documents/working-dir/pearai-app/extensions/pearai-submodule   main  python3 extensions/vscode/pearai_tutorial.py
a
b
c
Traceback (most recent call last):
  File "/Users/nathanan/Documents/working-dir/pearai-app/extensions/pearai-submodule/extensions/vscode/pearai_tutorial.py", line 56, in <module>
    print_list(["a", "b", "c"])
  File "/Users/nathanan/Documents/working-dir/pearai-app/extensions/pearai-submodule/extensions/vscode/pearai_tutorial.py", line 52, in print_list
    print(l[i])
IndexError: list index out of range
 ✘ nathanan@Nathans-MacBook-Air  ~/Documents/working-dir/pearai-app/extensions/pearai-submodule   main 

**Comment by nang-dev** [comment]
https://github.com/trypear/pearai-submodule/pull/47

**Comment by nang-dev** [comment]
I fixed :D
