### ISSUE TITLE
Setup Pear AI for development

### ISSUE THREAD

**Issue by botraunak** [trypear/pearai-app#139]
I am trying to setup the pear AI editor for local development and work on issues, I followed the steps mentioned Contributing.md, when I try to run the build I am faced with the following error

```
Executing task: node build/lib/preLaunch.js 

yarn run v1.22.22
$ node build/lib/electron
✨  Done in 0.84s.
[17:04:27] Synchronizing built-in extensions...
[17:04:27] You can manage built-in extensions with the --builtin flag
[17:04:27] Downloading extension: ms-vscode.js-debug-companion@1.1.2 ...
[17:04:27] Downloading extension: ms-vscode.js-debug@1.91.0 ...
[17:04:27] Downloading extension: ms-vscode.vscode-js-profile-table@1.0.9 ...
/Users/settraunak/Developer/vscode/pearai-app/build/lib/fetch.js:81
            throw new Error(err);
                  ^

Error: Request https://walrus-backup-app-sgqep.ondigitalocean.app/pearai-backup-server-api/gallery/publishers/ms-vscode/vsextensions/vscode-js-profile-table/1.0.9/vspackage failed with status code: 500
    at fetchUrl (/Users/settraunak/Developer/vscode/pearai-app/build/lib/fetch.js:81:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Emitted 'error' event on Stream instance at:
    at Stream.onerror (node:internal/streams/legacy:63:12)
    at Stream.emit (node:events:519:28)
    at Stream.emit (node:domain:488:12)
    at next (/Users/settraunak/Developer/vscode/pearai-app/node_modules/map-stream/index.js:75:19)
    at /Users/settraunak/Developer/vscode/pearai-app/node_modules/map-stream/index.js:85:7
    at /Users/settraunak/Developer/vscode/pearai-app/build/lib/fetch.js:31:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.9.0
```

**Comment by jujugary** [comment]
Having a very similar issue. Getting this error:

 Error: Request https://walrus-backup-app-sgqep.ondigitalocean.app/pearai-backup-server-api/gallery/publishers/ms-vscode/vsextensions/js-debug/1.91.0/vspackage failed with status code: 500
