### ISSUE TITLE
[Medium] [Submodule+Server] Bug: Token refresh not working

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#204]
![Screenshot 2024-07-17 at 7 30 10 PM](https://github.com/user-attachments/assets/d422c034-a645-4f9e-a94b-ed8a17f37688)

It should be refreshing!

We already check if the token is expired using:

https://github.com/trypear/pearai-submodule/blob/971ad37637d257b6f7033805d4843f3df142619a/core/db/token.ts#L43

and it should be updated:

https://github.com/trypear/pearai-submodule/blob/971ad37637d257b6f7033805d4843f3df142619a/core/llm/llms/PearAIServer.ts#L18

Basically, there is an

Access Token and a Refresh Token

On the client side (pearai-submodule), it checks if it the token is expired. It either does not detect it is expired correctly, or does not update correctly.

It passes the new accessToken (or apiKey, same thing in this case) to the server.

On the server side (pearai-server), it checks if the token is expired, and it is saying it is expired

## How to reproduce

Make the server side return 401 error locally, and this error will come up

**Comment by nang-dev** [comment]
Nvm i can fix this

**Comment by Ellahinator** [comment]
We can implement auto-refresh like this:

https://supabase.com/docs/reference/javascript/auth-startautorefresh

**Comment by nang-dev** [comment]
interesting.. will look into this

so far i guess when we need to update it in local storage if it detects a change

**Comment by cqdev-co** [comment]
Currently working on it

**Comment by cqdev-co** [comment]
Monitor progress here: https://github.com/trypear/pearai-submodule/pull/112

**Comment by nang-dev** [comment]
Log of when it happens. 
```

[Extension Host] Attempting to get credentials... (at console.<anonymous> (/Applications/PearAI.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61776:26))
workbench.desktop.main.js:58161 [Extension Host] Access token is expired, attempting to refresh (at console.<anonymous> (/Applications/PearAI.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61776:26))
workbench.desktop.main.js:58161 [Extension Host] Error refreshing token, redirecting to login: AuthApiError: Invalid Refresh Token: Already Used
    at handleError2 (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:84061:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _handleRequest (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:84104:9)
    at _request (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:84087:21)
    at /Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:85877:20
    at /Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:83797:30 (at console.<anonymous> (/Applications/PearAI.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61776:26))
workbench.desktop.main.js:123787   ERR [Extension Host] Error checking token expiration: ReferenceError: window is not defined
    at checkTokens (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:86903:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PearAIServer._streamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:87021:26)
    at PearAIServer.streamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:36232:30)
    at llmStreamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:374401:23)
    at UniqueContainer.value (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:374667:29)
workbench.desktop.main.js:58161 [Extension Host] Error checking token expiration: ReferenceError: window is not defined
    at checkTokens (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:86903:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PearAIServer._streamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:87021:26)
    at PearAIServer.streamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:36232:30)
    at llmStreamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:374401:23)
    at UniqueContainer.value (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:374667:29) (at console.<anonymous> (/Applications/PearAI.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61776:26))
log @ workbench.desktop.main.js:58161
$logExtensionHostMessage @ workbench.desktop.main.js:325885
S @ workbench.desktop.main.js:326516
Q @ workbench.desktop.main.js:326501
M @ workbench.desktop.main.js:326442
L @ workbench.desktop.main.js:326369
(anonymous) @ workbench.desktop.main.js:326248
y @ workbench.desktop.main.js:16700
fire @ workbench.desktop.main.js:16729
fire @ workbench.desktop.main.js:89909
port.onmessage @ workbench.desktop.main.js:344157
workbench.desktop.main.js:58161 [Extension Host] Error: Error: HTTP 401 Unauthorized from https://stingray-app-gb2an.ondigitalocean.app/pearai-server-api2/server_chat

{"error":"Token has expired"}

    at customFetch (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:36104:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:35856:26)
    at PearAIServer._streamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:87050:26)
    at PearAIServer.streamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:36232:30)
    at llmStreamChat (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:374401:23)
    at UniqueContainer.value (/Applications/PearAI.app/Contents/Resources/app/extensions/pearai.pearai-0.0.1/out/extension.js:374667:29) (at console.<anonymous> (/Applications/PearAI.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61776:26))
workbench.desktop.main.js:123787   ERR [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "aba75193-9226-41b5-b9ba-1bcd027365c7",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "```proxy_service.py (25-88)\n\ndef handle_server_chat(auth: Optional[Auth], span: Span, json_data):\n    # TODO: We should log to traces why the request failed not to the client (for security purposes)\n    if not auth:\n        return jsonify({\"error\": \"Authentication is required\"}), 403\n\n    token = auth.token\n    if not token:\n        return jsonify({\"error\": \"Token is missing\"}), 403\n\n    user_id = auth.get_user_id()\n    if not user_id:\n        return jsonify({\"error\": \"User ID is missing\"}), 403\n\n    span.set_attribute(\"user_id\", user_id)\n\n    # Check if user is subscribed\n    subscription = get_subscription_use_user(token, user_id)\n\n    if not subscription or subscription.status != \"active\":\n        code = 403\n        telem_utils.complete_span(span, code)\n        return (\n            jsonify(\n                {\n                    \"error\": \"User subscription is not active. Sign up at https://trypear.ai, or report an issue on the PearAI Discord.\"\n                }\n            ),\n            code,\n        )\n\n    # Check the quota based on users total requests this month\n    quota_group = \"total-requests\"\n\n    # initialize the users quota\n    if not quota.has_active_quota(user_id, quota_group):\n        profile = get_profile(token, user_id)\n        pricing = get_pricing_by_tier(subscription.pricing_tier)\n\n        quota.create_user_quota(\n            user_id=user_id,\n            quota_name=quota_group,\n            # use monthly_requests for quota because we reset the quota monthly\n            max_quota=pricing.monthly_requests if pricing else None,\n            initial_value=profile.requests_used if profile else 0,\n        )\n\n    quota_details = quota.get_user_quota_details(user_id, quota_group)\n\n    span.set_attribute(\"used_quota\", quota_details[\"used_quota\"])\n\n    if quota_details[\"quota_remaining\"] <= 0:\n        code = 403\n        telem_utils.complete_span(span, code)\n        return (\n            jsonify({\"error\": \"Quota exceeded\", \"details\": quota_details}),\n            code,\n        )\n    quota.increment_user_quota(user_id, quota_group)\n    # Todo: Abstract this to use classes so we can use different LLM's\n    # result = handle_stream_chat(span, json_data) OpenAI Service\n    result = handle_stream_chat(span, json_data)\n    return result\n\n```\nif get_config().DEV_ENABLED IS TRUE IT SHOULD SKIP ALL THE QUOTA STUFF"
            }
          ]
        }
      ],
      "title": "PearAI Server",
      "completionOptions": {}
    }
  }
}
workbench.desktop.main.js:58161 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "aba75193-9226-41b5-b9ba-1bcd027365c7",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "```proxy_service.py (25-88)\n\ndef handle_server_chat(auth: Optional[Auth], span: Span, json_data):\n    # TODO: We should log to traces why the request failed not to the client (for security purposes)\n    if not auth:\n        return jsonify({\"error\": \"Authentication is required\"}), 403\n\n    token = auth.token\n    if not token:\n        return jsonify({\"error\": \"Token is missing\"}), 403\n\n    user_id = auth.get_user_id()\n    if not user_id:\n        return jsonify({\"error\": \"User ID is missing\"}), 403\n\n    span.set_attribute(\"user_id\", user_id)\n\n    # Check if user is subscribed\n    subscription = get_subscription_use_user(token, user_id)\n\n    if not subscription or subscription.status != \"active\":\n        code = 403\n        telem_utils.complete_span(span, code)\n        return (\n            jsonify(\n                {\n                    \"error\": \"User subscription is not active. Sign up at https://trypear.ai, or report an issue on the PearAI Discord.\"\n                }\n            ),\n            code,\n        )\n\n    # Check the quota based on users total requests this month\n    quota_group = \"total-requests\"\n\n    # initialize the users quota\n    if not quota.has_active_quota(user_id, quota_group):\n        profile = get_profile(token, user_id)\n        pricing = get_pricing_by_tier(subscription.pricing_tier)\n\n        quota.create_user_quota(\n            user_id=user_id,\n            quota_name=quota_group,\n            # use monthly_requests for quota because we reset the quota monthly\n            max_quota=pricing.monthly_requests if pricing else None,\n            initial_value=profile.requests_used if profile else 0,\n        )\n\n    quota_details = quota.get_user_quota_details(user_id, quota_group)\n\n    span.set_attribute(\"used_quota\", quota_details[\"used_quota\"])\n\n    if quota_details[\"quota_remaining\"] <= 0:\n        code = 403\n        telem_utils.complete_span(span, code)\n        return (\n            jsonify({\"error\": \"Quota exceeded\", \"details\": quota_details}),\n            code,\n        )\n    quota.increment_user_quota(user_id, quota_group)\n    # Todo: Abstract this to use classes so we can use different LLM's\n    # result = handle_stream_chat(span, json_data) OpenAI Service\n    result = handle_stream_chat(span, json_data)\n    return result\n\n```\nif get_config().DEV_ENABLED IS TRUE IT SHOULD SKIP ALL THE QUOTA STUFF"
            }
          ]
        }
      ],
      "title": "PearAI Server",
      "completionOptions": {}
    }
  }
} (at console.<anonymous> (/Applications/PearAI.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61776:26))
log @ workbench.desktop.main.js:58161
$logExtensionHostMessage @ workbench.desktop.main.js:325885
S @ workbench.desktop.main.js:326516
Q @ workbench.desktop.main.js:326501
M @ workbench.desktop.main.js:326442
L @ workbench.desktop.main.js:326369
(anonymous) @ workbench.desktop.main.js:326248
y @ workbench.desktop.main.js:16700
fire @ workbench.desktop.main.js:16729
fire @ workbench.desktop.main.js:89909
port.onmessage @ workbench.desktop.main.js:344157
workbench.desktop.main.js:234705 Error: HTTP 401 Unauthorized from https://stingray-app-gb2an.ondigitalocean.app/pearai-server-api2/server_chat  {"error":"Token has expired"}
```

**Comment by nang-dev** [comment]
<img width="834" alt="Screenshot 2024-07-25 at 3 01 21 PM" src="https://github.com/user-attachments/assets/f3134b87-5fd6-417c-aa73-1f4709ed5743">

**Comment by cqdev-co** [comment]
Working on Server-side: https://github.com/trypear/pearai-server/pull/111

**Comment by nang-dev** [comment]
Ohhh okay, this is interesting.

This is whats happening:

submodule has accessToken A and refreshToken B

refreshSession is totally fine, as many times as you want.

you get 
 accessToken C and refreshToken D
 accessToken E and refreshToken F
and so on...

however, when the user logs in again, it gets refreshToken B again.

so then you only have refreshToken B, and its already used so you cant refreshSession

**Comment by nang-dev** [comment]
So we either need to:

On landing page: if theres an auth request, we need to refresh session when theres a login

On submodule: when we login, we try to refresh session. If it doesnt work ,dont take the params. Refresh session using our own refresh session

**Comment by nang-dev** [comment]
NVM.

https://cdn.discordapp.com/attachments/1267978653325856779/1268003472712667176/Screenshot_2024-07-30_at_5.33.01_PM.png?ex=66aad7c2&is=66a98642&hm=d6d969df3d39350c3c3cdfe7fa4042f4be86a50b77ad3eceb00eb0d35f062668&


My proposed solution is to have another sign in page on landing-page JUST for the app

**Comment by nang-dev** [comment]
Solved for now by allowing token refresh
