### ISSUE TITLE
Does not support the ssh-remote plugin, incompatible versions

### ISSUE THREAD

**Issue by forrany** [trypear/pearai-app#9]
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/959fb424-cfe8-4ef1-b6de-b72fe65dbdbc">

A lot of my code is on a remote development machine, and after installing pearAI, I found that the ssh functionality was not working, and I opened the plugin only to find that it was incompatible with the version.

If I can't use the ssh remote development function, I basically can't use this editor, I hope to support it soon!

**Comment by Fryingpannn** [comment]
Noted!

**Comment by bpawnzZ** [comment]
has this not been fixed??

**Comment by berrones** [comment]
Still has not been fixed. Using PearAI and Coder: [17:27:34.693] Resolver error: Error: Remote - SSH is only supported in Microsoft versions of VS Code
	at t.assertVSDA (/home/adam/.pearai/extensions/ms-vscode-remote.remote-ssh-0.116.1/out/extension.js:2:833690)
	at t.resolve (/home/adam/.pearai/extensions/ms-vscode-remote.remote-ssh-0.116.1/out/extension.js:2:772042)
	at /home/adam/.pearai/extensions/ms-vscode-remote.remote-ssh-0.116.1/out/extension.js:2:1055263
	at $ryc.d (file:///opt/PearAI/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73992:11)
	at $ryc.withProgress (file:///opt/PearAI/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73977:17)
	at Object.withProgress (file:///opt/PearAI/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:78725:32)
	at T.resolve (/home/adam/.pearai/extensions/ms-vscode-remote.remote-ssh-0.116.1/out/extension.js:2:1054849)
	at async $tzc.$resolveAuthority (file:///opt/PearAI/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:47699:20)
[17:27:34.698] ------

**Comment by bpawnzZ** [comment]
> Still has not been fixed. Using PearAI and Coder: [17:27:34.693] Resolver error: Error: Remote - SSH is only supported in Microsoft versions of VS Code at t.assertVSDA (/home/adam/.pearai/extensions/ms-vscode-remote.remote-ssh-0.116.1/out/extension.js:2:833690) at t.resolve (/home/adam/.pearai/extensions/ms-vscode-remote.remote-ssh-0.116.1/out/extension.js:2:772042) at /home/adam/.pearai/extensions/ms-vscode-remote.remote-ssh-0.116.1/out/extension.js:2:1055263 at $ryc.d (file:///opt/PearAI/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73992:11) at $ryc.withProgress (file:///opt/PearAI/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73977:17) at Object.withProgress (file:///opt/PearAI/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:78725:32) at T.resolve (/home/adam/.pearai/extensions/ms-vscode-remote.remote-ssh-0.116.1/out/extension.js:2:1054849) at async $tzc.$resolveAuthority (file:///opt/PearAI/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:47699:20) [17:27:34.698] ------

Frustrating man..  I would use this product over vscodium if this one feature worked.

**Comment by sufianWG** [comment]
need to fix this issue ASAP, even other Remote-SSH extensions from VSX Marketplace doesn't work in PearAi.
I  think, should have its own Remote-SSH functionality in PearAi as like "Windsurf"..
